### ISSUE TITLE
배너의 크기 (반응형)

### ISSUE THREAD

**Issue by seonmi1908** [tebica/opengirok#10]
반응형으로 만드실거라면, 브라우저의 크기별로 배너의 크기가 변형되어야 할 것 같은데요.
그럼 코딩으로 해결해야하나요?
아니면 크기별로 반응형 배너 이미지를 만들어두는 것인가요????

**Comment by avecjoeun** [comment]
하단3개 배너 모바일 메인에서 삭제. 링크처리도 노노
