### ISSUE TITLE
mobile 뷰 지원

### ISSUE THREAD

**Issue by tebica** [tebica/opengirok#3]

**Comment by avecjoeun** [comment]
민우쌤과 이야기했던것 잊어버리지 않기 위해 메모해두어용
-모바일은 반응형스킨을 사용 (티스토리 모바일 지원 사용x) 
-모바일 메인 페이지는 이미지 없이 텍스트만 보여주는 걸로
-선 개발 -> 후 디자인 입히기 순서로
-모바일 페이지 배너는 데스크탑 메인페이지 배너 3개만 남기고 다 없애기  

@tebica 잘못 메모된 부분 있으면 말씀해주세용ㅎㅎ

**Comment by tebica** [comment]
완성!
