### ISSUE TITLE
표 레이아웃이 이상합니다. 

### ISSUE THREAD

**Issue by seonmi1908** [tebica/opengirok#35]
민욱님 고생많으십니다~
땡글님 안녕하세요~
벨라입니다. 
http://www.opengirok.or.kr/4472
페이지를 보면 표 레이아웃이 이상해요..
혹 개편하면 이런 부분도 수정이 될까요??  
@tebica @DDanggle

**Comment by tebica** [comment]
글 콘텐츠의 문제. 나중에 해결
