### ISSUE TITLE
상단 SNS 아이콘과 메인 슬라이드 버튼 아이콘 png 파일입니다

### ISSUE THREAD

**Issue by seonmi1908** [tebica/opengirok#38]
좌표형으로 저장했는데요, 혹 각가 개별파일이 필요하신 거면 알려주세요. 
파일은 저희 드라이브에도 icon 이라는 폴더에 넣어두겠습니다.
![icon](https://cloud.githubusercontent.com/assets/24801300/24070517/56a7eb6a-0c02-11e7-8cc2-f2fb911bcd0f.png)

@DDanggle  @tebica  @lexifdev

**Comment by tebica** [comment]
적용 완료. 확인후 close 예정.

**Comment by tebica** [comment]
적용완료 되었으므로 일단 닫음
