### ISSUE TITLE
최종 메인화면 디자인과 간격 jpg 파일입니다. 

### ISSUE THREAD

**Issue by seonmi1908** [tebica/opengirok#40]
최종 메인화면 디자인과 간격 jpg 파일입니다. 
@DDanggle 
![20170318 -final-05](https://cloud.githubusercontent.com/assets/24801300/24190387/e6504330-0f2b-11e7-8420-537fbb1ab322.jpg)
![20170322- final-07](https://cloud.githubusercontent.com/assets/24801300/24190388/e6742200-0f2b-11e7-92a3-affe3b982151.jpg)
![20170322- -final-05](https://cloud.githubusercontent.com/assets/24801300/24190391/e68cb950-0f2b-11e7-88d9-fadd57d4280e.jpg)
![20170322- -final-07](https://cloud.githubusercontent.com/assets/24801300/24190392/e6905d58-0f2b-11e7-8084-bdbe98ff35c6.jpg)

**Comment by tebica** [comment]
완료되어서 닫습니다.
