### ISSUE TITLE
메뉴에 마우스 오버시 홍보 이미지가 랜덤하게 보이기

### ISSUE THREAD

**Issue by seonmi1908** [tebica/opengirok#42]
@DDanggle  @tebica  @lexifdev 

상단 메뉴에 마우스 오버하면 
왼쪽 상단에 홍보 이미지가 랜덤하게 등장했으면 좋겠습니다.
가능할까요? 

![1](https://cloud.githubusercontent.com/assets/24801300/24232420/47ad2178-0fce-11e7-9822-38555942a74a.jpg)

**Comment by tebica** [comment]
나중에 :)
