### ISSUE TITLE
모바일 메인 페이지에는 어떤 카테고리 글을 보여주까

### ISSUE THREAD

**Issue by avecjoeun** [tebica/opengirok#46]
정공센 논의 필요
 -전체글보기?
 -카테고리 두세개- 카테고리당 글 다섯개 정도씩? 
 등등

**Comment by avecjoeun** [comment]
오늘의정보공개청구- 10개
이화동광장-5개
공지사항-2개 
로 결정 땅땅

**Comment by tebica** [comment]
회의에서 데스트탑과 모바일 일단 글 개수 같도록함
