### ISSUE TITLE
우측배너 디자인 정리 

### ISSUE THREAD

**Issue by avecjoeun** [tebica/opengirok#47]
통일성있는 디자인으로 
배경색(회색?)

**Comment by tebica** [comment]
이 이슈는 일단 닫을까요? 우측 배너 디자인은 통일은 안되었네요?
지윤님이나 다른 분께 부탁드리는건 어떨까요?

**Comment by avecjoeun** [comment]
배너 디자인은 다른 디자이너분이 배경 만들어 주신게 있는데 지금 걸어놓을 배너가 많지 않아서 그냥 두었어용~ 이슈 닫을게요!
