### ISSUE TITLE
화면줄일때 글자겹침 외

### ISSUE THREAD

**Issue by avecjoeun** [tebica/opengirok#48]
pc화면에서 창을 줄이면 메인페이지 슬라이드 글자가 사진과 겹쳐서 보여용ㅠ

![default](https://user-images.githubusercontent.com/24791807/34548512-dad18526-f145-11e7-950a-b06c998ac69d.jpg)

**Comment by avecjoeun** [comment]
+ 창을 어느정도 줄이거나 모바일페이지로 가면 맨 위에 정보공개센터 로고를 눌러도 메인페이지로 이동이 안돼용ㅠ.ㅠ

**Comment by tebica** [comment]
현재 슬라이드바를 위한 HTML이 날아가서 슬라이드바 보여지지 않음.

**Comment by tebica** [comment]
슬라이더를 제거하기때문에 닫음
