### ISSUE TITLE
카테고리 게시판형/ 글 표시형 정리 

### ISSUE THREAD

**Issue by avecjoeun** [tebica/opengirok#50]
1. 스킨 설정을 목록+글로 할 때,
글이 하나밖에 없는 메뉴(소개, 알권리이야기 등)는 ok
<오늘의 정보공개청구> 같이 게시글이 많은 메뉴는 설정한 목록수와 글수가 한페이지에 쭉 나타남 
 => 전체목록 파악이 불가능+스크롤이 길어짐

2. 스킨 설정을 목록만 보여주기로 할때 
=> 기존 홈페이지 처럼 센터소개나 제도 소개 페이지도 목록으로만 표시됨

* 소개 등 단일 글 메뉴는 '페이지'기능 이용가능
문제1_ 스킨 html편집에서 url넣으면 된다고 하는데 어떡하라는건지 잘 모르겠어용...
문제2_html모드 지원 안됨 (추후 디자인은 그대로 있구 내용만 수정하는 것이 약간 어려워 질 수 있음..) 
 => html모드는 가능한 걸로 확인됨 *_* => http://blog.waanee.com/80 참고

**Comment by tebica** [comment]
@avecjoeun 이거 리뷰해주시고 필요 없으면 Close 해주세요~

**Comment by avecjoeun** [comment]
넵 close 합니다!
