### ISSUE TITLE
전체보기 목록 제목크기 수정

### ISSUE THREAD

**Issue by avecjoeun** [tebica/opengirok#54]
모바일에서만 전체보기 목록에 있는 제목 폰트 사이즈 2/3 정도로 조정
![inkedphoto_2018-10-02_14-39-15_li](https://user-images.githubusercontent.com/24791807/46331095-26c69800-c651-11e8-934f-e1570e76236d.jpg)

**Comment by tebica** [comment]
일단 크기 줄였습니다. 더 줄여야 하면 말해주세요-
