### ISSUE TITLE
모바일에서 페이징 크기 줄이기

### ISSUE THREAD

**Issue by avecjoeun** [tebica/opengirok#57]
![default](https://user-images.githubusercontent.com/24791807/46332224-84a9ae80-c656-11e8-8f71-abc2cbca76be.PNG)

모바일 페이징 크기 대폭 축소 (한 줄 안에 다 들어오게 수정)

**Comment by tebica** [comment]
수정완료. 확인후 닫아주세요.
![image](https://user-images.githubusercontent.com/1404067/46626782-5145b300-cb73-11e8-8dfe-699033b7a938.png)

**Comment by avecjoeun** [comment]
와웅 감사합니당 확인완료~
