### ISSUE TITLE
게시판 표시 순서

### ISSUE THREAD

**Issue by avecjoeun** [tebica/opengirok#58]
![default](https://user-images.githubusercontent.com/24791807/46332508-b5d6ae80-c657-11e8-82a3-cfc0af6b46b1.PNG)

게시판 표시 순서
날짜-제목 => 제목- 날짜 순으로 변경

**Comment by tebica** [comment]
수정 완료. 확인하고 닫아주세요-

**Comment by avecjoeun** [comment]
넵 확인완료입니당~
