### ISSUE TITLE
하단배너 링크연결 필요

### ISSUE THREAD

**Issue by avecjoeun** [tebica/opengirok#59]
![default](https://user-images.githubusercontent.com/24791807/46332565-f6362c80-c657-11e8-8bfa-39605dc3a6ac.PNG)

하단 배너에 링크연결 

1. 예정만세 
http://www.podbbang.com/ch/11525

2. 세월호아카이브
https://sewolarchive.org/

3. 방사능와치
http://www.nukeknock.net/

**Comment by tebica** [comment]
작업 완료-
