### ISSUE TITLE
모바일 버전에서 정보공개청구관련사이트 링크

### ISSUE THREAD

**Issue by seonmi1908** [tebica/opengirok#8]
![default](https://cloud.githubusercontent.com/assets/24801300/21633343/a793a2d0-d291-11e6-8799-797eae89b616.jpg)

모바일 버전에서 정보공개청구관련사이트 링크
어떻게 보여줄까요?

클릭하면 펼쳐지는 펼침메뉴(드랍다운)가 좋을까요?
아니면 아예 뺄까요? 
아니면 내용이 길더라도 첫 화면에서 다 보이게 할까요? ^^
https://goo.gl/GsH4oq

@avecjoeun

**Comment by avecjoeun** [comment]
관련사이트링크는 모바일에서 빼는걸로~
